services:
  bot_eth:
    build: .
    image: bot_eth
    container_name: bot_eth
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - ./venv/.env
    environment:
      - SYMBOL=ETH
    restart: unless-stopped
    working_dir: /app
    command: python -m src.main ETH
  bot_btc:
    build: .
    image: bot_btc
    container_name: bot_btc
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - ./venv/.env
    environment:
      - SYMBOL=BTC
    restart: unless-stopped
    working_dir: /app
    command: python -m src.main BTC