services:
  bot_arbitratge:
    build: .
    image: bot_arbitratge
    container_name: bot
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    restart: unless-stopped
    # Uncomment and set if you want to map ports
    # ports:
    #   - "8000:8000"
    # Add more volumes as needed, e.g.:
    #   - ./data:/app/data
    # Set user if you want to match host permissions
    # user: "1000:1000"
    working_dir: /app
    command: python -m src.main
