services:
  bot_eth:
    build: .
    image: bot_eth
    container_name: bot_eth
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - SYMBOL=ETH
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    restart: unless-stopped
    working_dir: /app
    command: python -m src.main ETH
